// @ts-check
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import cloudflare from '@astrojs/cloudflare';
import tailwindcss from '@tailwindcss/vite';

// The public canonical URL of the deployed site.
// Override locally / on Cloudflare with the PUBLIC_SITE_URL env var.
const SITE_URL = process.env.PUBLIC_SITE_URL ?? 'https://websitehistoryviewer.com';

// https://astro.build/config
export default defineConfig({
  site: SITE_URL,

  // Multilingual routing. English stays at the root (no /en prefix) to preserve
  // existing URLs and SEO; every other locale is served under its own path
  // prefix (/es, /fr, /de, /hi) for distinct, indexable per-language URLs.
  //
  // `fallback` + `fallbackType: 'rewrite'` ships those localized URLs
  // immediately: any page that isn't translated yet renders the English content
  // *at the localized URL* (no redirect), so the routes are crawlable from day
  // one and progressively pick up real translations as the dictionary fills in.
  // Keep the locale list in sync with src/i18n/ui.ts.
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'es', 'fr', 'de', 'hi'],
    fallback: { es: 'en', fr: 'en', de: 'en', hi: 'en' },
    routing: {
      prefixDefaultLocale: false,
      fallbackType: 'rewrite',
    },
  },

  // Static by default for maximum performance & SEO. Individual dynamic
  // routes opt into on-demand rendering with `export const prerender = false`.
  output: 'static',

  // Cloudflare adapter enables on-demand (SSR) routes and Worker API endpoints.
  // `imageService: 'compile'` optimizes images for prerendered pages at build
  // time and passes remote images through at runtime (Sharp can't run on the
  // Workers runtime).
  adapter: cloudflare({
    imageService: 'compile',
    // The local Workers runtime (workerd, via miniflare's platform proxy)
    // crashes with a native access violation on some Windows machines — a
    // known workerd/Windows issue (cloudflare/workers-sdk#9858). We don't use
    // any Cloudflare bindings, sessions, or `locals.runtime` in app code, so
    // disabling the platform proxy lets `astro dev` run on plain Node/Vite and
    // avoids spawning workerd. Production builds/deploys are unaffected.
    platformProxy: { enabled: false },
  }),

  // Note: the sitemap is generated by hand at src/pages/sitemap.xml.ts so it can
  // include the on-demand /timeline/[domain] pages for curated popular sites.
  integrations: [mdx()],

  image: {
    // Allow Astro's <Image /> to optimize archived assets when we have them.
    domains: ['web.archive.org', 'archive.org', 'images.weserv.nl'],
    remotePatterns: [{ protocol: 'https' }],
  },

  vite: {
    // Cast via JSDoc: Astro bundles its own Vite copy, so the plugin's Vite
    // types don't structurally match Astro's. Harmless at runtime.
    plugins: [/** @type {any} */ (tailwindcss())],
  },

  prefetch: {
    prefetchAll: true,
    defaultStrategy: 'viewport',
  },
});
